[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
tui-textarea = "0.7.0"
server = {path = "../server"}
serde = "1.0.219"
serde_json = "1.0.140"
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
chrono = "0.4.41"
rand = "0.9.1"
